# Generated by Django 6.0.2 on 2026-02-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
