# Generated by Django 6.0.2 on 2026-02-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_notification_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularBlog',
            fields=[
            ],
            options={
                'verbose_name': 'Popular Blog',
                'verbose_name_plural': 'Popular Blogs',
                'ordering': ['-views'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.blog',),
        ),
    ]
